/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

window.MathJax={tex:{inlineMath:[["$","$"],["\\(","\\)"]],displayMath:[["$$","$$"],["\\[","\\]"]],processEscapes:!0,processEnvironments:!0,processRefs:!0},chtml:{matchFontHeight:!0,displayAlign:"center",displayIndent:"0",scale:1,adaptiveCSS:!0},options:{enableMenu:!1,enableExplorer:!1,enableAssistiveMml:!1,enableEnrichment:!1,menuOptions:{settings:{assistiveMml:!1,collapsible:!1,explorer:!1}},renderActions:{assistiveMml:[]}},startup:{ready:()=>{MathJax.startup.defaultReady(),console.log("MathJax initialized with all extensions")}}};
